# Generated by Django 6.0.4 on 2026-04-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_add_frequency_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
