# Generated by Django 6.0.4 on 2026-04-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('specialization', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Orthopedics', 'Orthopedics'), ('Neurology', 'Neurology'), ('Gynecology', 'Gynecology'), ('Ophthalmology', 'Ophthalmology'), ('ENT', 'Ear, Nose & Throat'), ('Psychiatry', 'Psychiatry'), ('Radiology', 'Radiology')], max_length=50)),
                ('qualification', models.CharField(max_length=200)),
                ('experience_years', models.IntegerField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_days', models.CharField(help_text='e.g., Mon, Tue, Wed', max_length=100)),
                ('available_time_start', models.TimeField()),
                ('available_time_end', models.TimeField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
